### ISSUE TITLE
Request Letter

### ISSUE THREAD

**Issue by MinLila** [miccaiif/FCMEF#1]
Thank you for your excellent work, I  wonder when your code will be available to the public?

**Comment by miccaiif** [comment]
Hello! Thank you for your attention! We apologize for the delay in releasing the code. We have been busy with other work during this period, but the code will be open-sourced soon! Thank you for your patience!

**Comment by miccaiif** [comment]
I appreciate your attention. Regrettably, I was away on vacation, which caused a delay in organizing and promptly releasing the source code. I am pleased to inform you that the code is now available as open source. Your patience during this process is greatly valued. Should you find this article and its accompanying code beneficial to your work, please consider citing it and reaching out to us for any further inquiries. We are committed to maintaining regular updates to the codebase.
