### ISSUE TITLE
code release

### ISSUE THREAD

**Issue by LYL1946734397** [miccaiif/FCMEF#2]
When will the code be released?

**Comment by miccaiif** [comment]
Codes will be available in 2 weeks!

**Comment by miccaiif** [comment]
I appreciate your attention. Regrettably, I was away on vacation, which caused a delay in organizing and promptly releasing the source code. I am pleased to inform you that the code is now available as open source. Your patience during this process is greatly valued. Should you find this article and its accompanying code beneficial to your work, please consider citing it and reaching out to us for any further inquiries. We are committed to maintaining regular updates to the codebase.
